ARG ALMA_VERSION=10
#ARG OIDC_AGENT_VERSION=4.5.2
ARG OIDC_AGENT_VERSION=5.3.8
ARG JWT_AGENT_VERSION=1.1.1

# ----- Base Stage -----
FROM almalinux:${ALMA_VERSION}-minimal AS base
ARG ALMA_VERSION
ARG OIDC_AGENT_VERSION
ARG JWT_AGENT_VERSION

RUN microdnf update -y \
    && microdnf install -y epel-release \
    && if [ "$ALMA_VERSION" = "10" ]; then \
        WEBKITGTK=webkit2gtk4.1; \
    else \
        WEBKITGTK=webkitgtk4; \
    fi \
    && echo "WEBKITGTK=${WEBKITGTK}" > /tmp/env_webkit \
    && microdnf install -y --enablerepo=crb --setopt=install_weak_deps=0 \
    # Common runtime libraries and utilities
    libsodium \
    libmicrohttpd \
    libsecret \
    qrencode \
    ${WEBKITGTK} \
    jq \
    curl \
    tar \
    && microdnf clean all

# ----- Builder Stage -----
FROM base AS builder
ARG ALMA_VERSION
ARG OIDC_AGENT_VERSION
ARG JWT_AGENT_VERSION

# Install build-time packages
RUN . /tmp/env_webkit \
    && microdnf install -y --enablerepo=crb --setopt=install_weak_deps=0 \
    # To build jwt-agent
    git \
    golang \
    pandoc \
    # To build oidc-agent
    make \
    patch \
    help2man \
    gcc \
    gcc-c++ \
    libcurl-devel \
    libsodium-devel \
    libmicrohttpd-devel \
    libsecret-devel \
    qrencode-devel \
    ${WEBKITGTK}-devel \
    desktop-file-utils \
    # To get gosu
    wget \
    gnupg2 \
    && microdnf clean all

WORKDIR /tmp

# Build and install jwt-agent to /opt/jwt-agent
RUN git clone --depth 1 --branch $JWT_AGENT_VERSION \
    https://github.com/oss-tsukuba/jwt-agent.git \
    && cd jwt-agent \
    && make -j$(nproc) \
    && mkdir -p /opt/jwt-agent/bin \
    && make install PREFIX=/opt/jwt-agent

COPY docker/oidc-agent.patch .

# Build and install oidc-agent to /opt/oidc-agent
RUN OIDC_AGENT_NAME=oidc-agent-${OIDC_AGENT_VERSION} \
    && curl -L -o ${OIDC_AGENT_NAME}.tar.gz \
       https://github.com/indigo-dc/oidc-agent/archive/refs/tags/v${OIDC_AGENT_VERSION}.tar.gz \
    && tar xzf ${OIDC_AGENT_NAME}.tar.gz \
    && cd ${OIDC_AGENT_NAME} \
    && (sed -i 's/DEFINE_USE_CJSON_SO =/#DEFINE_USE_CJSON_SO =/g' Makefile || :) \
    && (sed -i 's/DEFINE_USE_LIST_SO =/#DEFINE_USE_LIST_SO =/g' Makefile || :) \
    && (sed -i 's/DEFINE_USE_MUSTACHE_SO =/#DEFINE_USE_MUSTACHE_SO =/g' Makefile || :) \
    && (sed -i 's/@ln -s /@ln -sf /g' Makefile || :) \
    && if [ "$ALMA_VERSION" = "10" ]; then \
      patch -p0 < /tmp/oidc-agent.patch \
      && sed -i 's/webkit2gtk-4.0/webkit2gtk-4.1/g' Makefile; \
    fi \
    && make -j$(nproc) \
    && make install_lib PREFIX=/opt/oidc-agent \
    && make install PREFIX=/opt/oidc-agent \
    && make post_install \
    && find /opt/oidc-agent/

# Install gosu
# (From https://github.com/tianon/gosu/blob/master/INSTALL.md)
ENV GOSU_VERSION=1.19
RUN set -eux; \
	\
	rpmArch="$(rpm --query --queryformat='%{ARCH}' rpm)"; \
	case "$rpmArch" in \
		aarch64) dpkgArch='arm64' ;; \
		armv[67]*) dpkgArch='armhf' ;; \
		i[3456]86) dpkgArch='i386' ;; \
		ppc64le) dpkgArch='ppc64el' ;; \
		riscv64 | s390x | loongarch64) dpkgArch="$rpmArch" ;; \
		x86_64) dpkgArch='amd64' ;; \
		*) echo >&2 "error: unknown/unsupported architecture '$rpmArch'"; exit 1 ;; \
	esac; \
	wget -O /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$dpkgArch"; \
	wget -O /usr/local/bin/gosu.asc "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$dpkgArch.asc"; \
	\
# verify the signature
	export GNUPGHOME="$(mktemp -d)"; \
	gpg --batch --keyserver hkps://keys.openpgp.org --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4; \
	gpg --batch --verify /usr/local/bin/gosu.asc /usr/local/bin/gosu; \
	gpgconf --kill all; \
	rm -rf "$GNUPGHOME" /usr/local/bin/gosu.asc; \
	\
	chmod +x /usr/local/bin/gosu; \
# verify that the binary works
	gosu --version; \
	gosu nobody true

# Build and install hpcissh-clients to /opt/hpcissh-clients
COPY . /tmp/hpcissh-clients
RUN cd /tmp/hpcissh-clients \
    && make prefix=/opt/hpcissh-clients \
    && make install prefix=/opt/hpcissh-clients

# ----- Final Stage -----
FROM base
ARG ALMA_VERSION
ARG OIDC_AGENT_VERSION
ARG JWT_AGENT_VERSION

# Install final stage runtime packages
RUN . /tmp/env_webkit \
    && microdnf install -y --enablerepo=crb --setopt=install_weak_deps=0 \
    # For hpcissh
    sshpass \
    openssh-clients \
    ncurses \
    # For oidc-agent
    procps-ng \
    # For jwt-agent
    syslog-ng \
    # Useful packages
    glibc-langpack-en \
    glibc-langpack-ja \
    glibc-locale-source \
    rsync \
    sshfs \
    sudo \
    which \
    vim-minimal \
    less \
    openssl \
    man \
    zsh \
    tcsh \
    && microdnf clean all

# Copy all artifacts from builder
COPY --from=builder /opt/hpcissh-clients /opt/hpcissh-clients
COPY --from=builder /opt/oidc-agent /opt/oidc-agent
COPY --from=builder /opt/jwt-agent /opt/jwt-agent
COPY --from=builder /usr/local/bin/gosu /usr/local/bin/gosu

# Set PATH and LD_LIBRARY_PATH
ENV PATH="/opt/hpcissh-clients/bin:/opt/oidc-agent/usr/bin:/opt/jwt-agent/bin:${PATH}"
RUN echo "/opt/oidc-agent/usr/lib/x86_64-linux-gnu" > /etc/ld.so.conf.d/oidc-agent.conf && ldconfig

COPY docker/syslog-ng.conf /etc/syslog-ng/hpci-syslog-ng.conf
COPY docker/entrypoint.sh /entrypoint.sh
COPY docker/test-container.sh /test-container.sh
COPY run-tests.sh /opt/run-tests-hpcissh.sh

ENV LANG=ja_JP.UTF-8 \
    TZ=Asia/Tokyo

WORKDIR /
USER root
ENTRYPOINT ["/bin/bash", "/entrypoint.sh"]
CMD ["__DEFAULT__"]
