@version: 4.8
@include "scl.conf"

source s_local {
    system();
    internal();
};

destination d_stdout {
    file("/dev/stdout");
    #file("/proc/1/fd/1");
};

destination d_messages {
    file("/var/log/messages" perm(0644));
};

log {
    source(s_local);
    #destination(d_stdout);
    destination(d_messages);
};
