#!/bin/bash

set -eu

source ${pkglibexecdir:-@pkglibexecdir@}/hpcissh-lib

usage() {
    echo "Usage: ${0} [sftp command option] host"
}

init_common "${@}"
get_token

RAW_ARGV=("sftp")
RAW_ARGV+=("${@}")

ARGV=()
for arg in `convert_sftp_arg "${RAW_ARGV[@]}"`; do
    ARGV+=("$arg")
done
ARGV=("${ARGV[@]:1}")

set +e
runssh sftp -P ${HPCISSH_PORT} ${SSH_BASIC_OPTS} "${ARGV[@]}"
RESULT=${?}
verify_hostname $RESULT
set -e
exit $RESULT
