#!/bin/bash

set -eu

CMD_ABS_PATH=`realpath $(which ${0})`
PARENT_DIR=`dirname ${CMD_ABS_PATH}`
source ${PARENT_DIR}/hpcissh-lib

load_common_config

# support jwt-agent and oidc-agent
get_token_ignore_expired
echo $OIDC_AT
