#!/bin/bash

set -eu

source ${pkglibexecdir:-@pkglibexecdir@}/hpcissh-lib

load_common_config

ISSUER=${OIDC_ISSUER}
SCOPES="openid hpci offline_access scitokens"
AUDIENCE="hpci"

if [ ${#} -eq 0 ];
then
    CONF_NAME="hpci"
else
    CONF_NAME=${1}
fi

oidc-sshconf "${ISSUER}" "${SCOPES}" "${AUDIENCE}" "${CONF_NAME}"
